# permissions for end users to view appprofiles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: appprofile-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kkarlon
    app.kubernetes.io/part-of: kkarlon
    app.kubernetes.io/managed-by: kustomize
  name: appprofile-viewer-role
rules:
- apiGroups:
  - core.kkarlon.io
  resources:
  - appprofiles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.kkarlon.io
  resources:
  - appprofiles/status
  verbs:
  - get
