# permissions for end users to edit callhomeconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: callhomeconfig-editor-role
rules:
- apiGroups:
  - core.kkarlon.io
  resources:
  - callhomeconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.kkarlon.io
  resources:
  - callhomeconfigs/status
  verbs:
  - get
