# permissions for end users to edit clusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: cluster-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kkarlon
    app.kubernetes.io/part-of: kkarlon
    app.kubernetes.io/managed-by: kustomize
  name: cluster-editor-role
rules:
- apiGroups:
  - core.kkarlon.io
  resources:
  - clusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.kkarlon.io
  resources:
  - clusters/status
  verbs:
  - get
