---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - core.kkarlon.io
  resources:
  - appprofiles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.kkarlon.io
  resources:
  - appprofiles/finalizers
  verbs:
  - update
- apiGroups:
  - core.kkarlon.io
  resources:
  - appprofiles/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - core.kkarlon.io
  resources:
  - callhomeconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.kkarlon.io
  resources:
  - callhomeconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - core.kkarlon.io
  resources:
  - callhomeconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - core.kkarlon.io
  resources:
  - clusterregistrations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.kkarlon.io
  resources:
  - clusterregistrations/finalizers
  verbs:
  - update
- apiGroups:
  - core.kkarlon.io
  resources:
  - clusterregistrations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - core.kkarlon.io
  resources:
  - clusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.kkarlon.io
  resources:
  - clusters/finalizers
  verbs:
  - update
- apiGroups:
  - core.kkarlon.io
  resources:
  - clusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - core.kkarlon.io
  resources:
  - profiles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.kkarlon.io
  resources:
  - profiles/finalizers
  verbs:
  - update
- apiGroups:
  - core.kkarlon.io
  resources:
  - profiles/status
  verbs:
  - get
  - patch
  - update
