apiVersion: apps/v1
kind: Deployment
metadata:
  name: kkarlon-controller
  namespace: kkarlon
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kkarlon-controller
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kkarlon-controller
    spec:
      containers:
      - command:
        - /kkarlon
        - controller
        - --argocd-config-path
        - /.argocd/config
        image: ghcr.io/kkarlonproj/kkarlon/controller:0.10.0
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        name: kkarlon-controller
        ports:
        - containerPort: 8081
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 60Mi
          requests:
            cpu: 100m
            memory: 60Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - all
          readOnlyRootFilesystem: false
          runAsNonRoot: false
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /.argocd
          name: argocd-creds
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      volumes:
      - name: argocd-creds
        secret:
          secretName: argocd-creds
          defaultMode: 0400
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kkarlon-appprof-ctrlr
  namespace: kkarlon
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kkarlon-appprof-ctrlr
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kkarlon-appprof-ctrlr
    spec:
      containers:
        - command:
            - /kkarlon
            - appprofilecontroller
            - --argocd-config-path
            - /.argocd/config
          image: ghcr.io/kkarlonproj/kkarlon/controller:0.10.0
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          name: kkarlon-appprof-ctrlr
          ports:
            - containerPort: 8081
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 60Mi
            requests:
              cpu: 100m
              memory: 60Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - all
            readOnlyRootFilesystem: false
            runAsNonRoot: false
            runAsUser: 0
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /.argocd
              name: argocd-creds
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      volumes:
        - name: argocd-creds
          secret:
            secretName: argocd-creds
            defaultMode: 0400
