apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io/foreground
  labels:
    karlon-cluster: example-1
    karlon-type: karlon-app
    managed-by: karlon
  name: example-1-karlon
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: ""
  source:
    helm:
      parameters:
      - name: global.clusterName
        value: example-1
      - name: global.kubeconfigSecretKeyName
        value: value
      - name: global.innerClusterNameWithDashSuffix
        value: mycluster-
    path: pkg/cluster/manifests
    repoURL: https://github.com/karlonproj/karlon.git
    targetRevision: v0.9.0
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - Prune=true
status:
  health: {}
  summary: {}
  sync:
    comparedTo:
      destination: {}
      source:
        repoURL: ""
    status: ""
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    karlon.io/profiles: frontend,backend
    karlon.io/basecluster-name: mycluster
    karlon.io/basecluster-repo-path: examples/clustertemplates/eks-managed-mpool
    karlon.io/basecluster-repo-revision: v0.10
    karlon.io/basecluster-repo-url: https://github.com/karlonproj/karlon.git
  finalizers:
  - resources-finalizer.argocd.argoproj.io/foreground
  labels:
    karlon-cluster: example-1
    karlon-type: cluster-app
    managed-by: karlon
  name: example-1
  namespace: argocd
spec:
  destination:
    namespace: example-1
    server: https://kubernetes.default.svc
  ignoreDifferences:
  - group: cluster.x-k8s.io
    jsonPointers:
    - /spec/replicas
    kind: MachineDeployment
  - group: controlplane.cluster.x-k8s.io
    jsonPointers:
    - /spec/version
    kind: AWSManagedControlPlane
  - group: infrastructure.cluster.x-k8s.io
    jsonPointers:
    - /spec
    kind: AWSMachineTemplate
  project: ""
  source:
    kustomize:
      namePrefix: example-1-
    repoURL: https://github.com/karlonproj/karlon.git
    path: examples/clustertemplates/eks-managed-mpool
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - Prune=true
